### ISSUE TITLE
建议更改默认快捷键 cmd + shift + t，这是个非常常用的内置快捷键

### ISSUE THREAD

**Issue by tjx666** [Simon-He95/vscode-toggle-dynamic-prop#2]
可选方案：
1. 换一个不是很常用的快捷键，至少不应该暂用 vscode 内置快捷键
2. 默认不配置快捷键，让用户自己配置
3. 考虑作为一个重构选项

可能不是很相关的问题：这个命令的 title 目前是中文，建议改成英文，如要要支持中文，建议使用 VSCode 内置的 i18n 方案

**Comment by Simon-He95** [comment]
快捷键冲突，用户完全可以使用 `keybings` 自己设置
